### ISSUE TITLE
MIDI input port *MUST* be migrated to Atom

### ISSUE THREAD

**Issue by jofemodo** [nicoroulet/moog#10]
Hi @nicoroulet !

We have been using the Raffo emulator with zynthian for a while, but suddenly, after a system update, it doesn't work any more. 

The problem is that the LV2 Event extension is totally deprecated and MIDI input port should be migrated to Atom.

I've been trying a little bit, but only got segfaults until now ....

**Comment by jofemodo** [comment]
Jalv 1.6.2 has already removed support for event and uri-map extensions:

https://drobilla.net/category/jalv/

As a result, currently the plugin doesn't run with Jalv.

**Comment by nicoroulet** [comment]
Thanks a lot for the report and the PR fixing the issue, and sorry for the delay.

**Comment by jofemodo** [comment]
It's a pleasure to help maintaining this beauty code ;-)
