### ISSUE TITLE
RaffoSynth's moog and LibraZiK-2

### ISSUE THREAD

**Issue by trebmuh** [nicoroulet/moog#8]
Hi @nicoroulet ,
I'm usually sending an email to the upstream developer for that but I can't find one for you. Hence this "issue".

Just to let you know that, as of today, RaffoSynth's moog 0.0.0~git7d267a0 has hit the LibraZiK-2's users repo.

Thanks for this nice moog-ish software!

PS: feel free to close this "issue" when you have read it.

**Comment by julianpalladino** [comment]
Hey there, @trebmuh!
I am a co-developer of RaffoSynth moog with my dear friend @nicoroulet, and I didn't want to miss this chance to thank you, @jofemodo and @jpcima for your interest in our synth and for adding it to LibraZiK-2.
We will try Librazik as well to check out your whole project! Cheers

**Comment by trebmuh** [comment]
Hi @julianpalladino and thanks for your nice words. I hope you'll like the LibraZiK-2 experience, let me know how it goes.
(Note: you can try it without installation thanks to the USB live ISO provided)
