### ISSUE TITLE
Change name to avoid trademark issues with Moog Music Inc.

### ISSUE THREAD

**Issue by fpesari** [nicoroulet/moog#9]
Hello,

I want to make an openSUSE package for this program but the "moog" name might cause trademark issues and I don't want users to be annoyed by it, could you please change it to something different? Thank you :smiley_cat:

**Comment by julianpalladino** [comment]
Hey there!
That's a cool idea! Would it be enough just to change the repository name? We would rename it to "RaffoSynth"

**Comment by fpesari** [comment]
That's fine :smile_cat:

**Comment by nicoroulet** [comment]
Done!
